# Generated by Django 5.0.7 on 2025-04-18 10:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_student_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('criteria', models.TextField(help_text='Eligibility criteria for the job')),
                ('selection_type', models.CharField(choices=[('normal', 'Normal Selection Process'), ('fast_track', 'Fast Track Selection')], default='normal', max_length=20)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_date_to_apply', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('shortlisted_oa', 'Shortlisted for Online Assessment'), ('completed_oa', 'Completed Online Assessment'), ('shortlisted_interview', 'Shortlisted for Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('preference_order', models.PositiveIntegerField(default=1)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functionality.job')),
            ],
            options={
                'unique_together': {('student', 'job')},
            },
        ),
    ]
